[[directory]]
name = "apple"
path = "/path/.moneyd/apple"

[[directory]]
name = "amex"
path = "/home/bmtron/.moneyd/amex"

[[directory]]
name = "citizens"
path = "/home/bmtron/.moneyd/citizens"

[[directory]]
name = "chase"
path = "/path/.moneyd/chase"